### ISSUE TITLE
Using the wrong bug emoji for this issue

### ISSUE THREAD

**Issue by liam-middlebrook** [niv/open-gpu-kernel-modules#2]
### NVIDIA Open GPU Kernel Modules Version

Any version

### Does this happen with the proprietary driver (of the same version) as well?

I cannot test this

### Operating System and Version

Any

### Kernel Release

Any

### Hardware: GPU

Any

### Describe the bug

The bug emoji used is currently :lady_beetle: which is `:lady_beetle:` not `:bug:`.

### To Reproduce

N/A

### Bug Incidence

Always

### Expected behaviour

![bug_1f41b](https://user-images.githubusercontent.com/3920942/168915822-2d46364c-bf60-4685-af61-bab8de33b693.png)
Above is an attachment of the bug emoji from Twemoji 4.0 according to emojipedia: https://emojipedia.org/twitter/twemoji-14.0/bug/

Per your requirements I have also attached a "bug report" below.
[bug-report.log.gz](https://github.com/niv/open-gpu-kernel-modules/files/8711761/bug-report.log.gz)

**Comment by niv** [comment]
~Fixed~ Bugged.
